import re
from enum import Enum

from tortoise import fields, Model
from tortoise.validators import RegexValidator


class Marketplace(str, Enum):
    """
    supported marketplaces
    """
    TWEEDEHANDS = "TWEEDEHANDS"


class ListingInfo(Model):
    """
    minimal listing info stored to compare with other listings
    """
    id = fields.CharField(pk=True, max_length=11, description="unique listing ID, generated by marketplace")
    title = fields.CharField(max_length=60)
    date = fields.DatetimeField(description="date when listing was published")
    marketplace = fields.CharEnumField(Marketplace)


class QueryInfo(Model):
    """
    query info to be monitored
    """
    id = fields.IntField(pk=True) # so it can be easily removed
    request_url = fields.CharField(
        unique=True,
        max_length=500,
        # update this! regex should be way broader
        validators=[RegexValidator(
            r'^https://www\.2dehands\.be/lrp/api/search\?.*',
            re.M)],
        description="url to use for GET request"
    )
    marketplace = fields.CharEnumField(Marketplace)
    query = fields.CharField(max_length=60)
