import re

from tortoise import Model, fields
from tortoise.validators import RegexValidator


class LatestListingInfoDB(Model):
    """
    stores per request_url the latest listing info
    """
    # we use item_id as the item_id and request_url are a composite key & ID is implcitly generated
    item_id = fields.CharField(max_length=11, description="unique listing ID, generated by 2dehands")
    request_url = fields.CharField(
        pk=True,
        max_length=500,
        # update this! regex should be way broader
        validators=[RegexValidator(
            r'^https://www\.2dehands\.be/lrp/api/search\?.*',
            re.M)],
        description="url to use for GET request"
    )
    title = fields.CharField(max_length=60)